import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

// ─── Traductions ──────────────────────────────────────────────────────────────
export const translations = {
  fr: {
    // Navigation
    nav: {
      dashboard: 'Tableau de bord',
      clients: 'Clients',
      invoices: 'Factures',
      newInvoice: 'Nouvelle facture',
      profile: 'Mon profil',
      logout: 'Déconnexion',
    },
    // Auth
    auth: {
      login: 'Connexion',
      register: 'Inscription',
      email: 'Email',
      password: 'Mot de passe',
      company: 'Nom de votre entreprise',
      companyPlaceholder: 'Mon Studio Créatif',
      emailPlaceholder: 'vous@exemple.fr',
      loginBtn: 'Se connecter',
      registerBtn: 'Créer mon compte',
      logging: 'Connexion...',
      creating: 'Création...',
      loginTitle: 'Bon retour !',
      registerTitle: 'Créer un compte',
      loginSubtitle: 'Connectez-vous pour accéder à votre tableau de bord',
      registerSubtitle: 'Commencez à facturer gratuitement en 30 secondes',
      terms: "En créant un compte, vous acceptez nos conditions d'utilisation.",
      heroTitle: 'Vos factures,',
      heroSubtitle: 'en 2 minutes.',
      heroDesc: 'La solution SaaS pensée pour les freelances. Créez, envoyez et suivez vos factures comme un pro.',
    },
    // Dashboard
    dashboard: {
      title: 'Tableau de bord',
      subtitle: "Vue d'ensemble de votre activité",
      totalRevenue: "Chiffre d'affaires total",
      collected: 'CA encaissé',
      toCashIn: 'À encaisser',
      activeClients: 'Clients actifs',
      revenueChart: 'Évolution du CA encaissé',
      statusChart: 'Répartition des statuts',
      topClients: 'Top clients',
      noData: "Aucune donnée — marquez des factures comme payées pour voir l'évolution.",
      noInvoice: 'Aucune facture pour le moment.',
      total: 'Total',
      drafts: 'Brouillons',
      sent: 'Envoyées',
      late: 'En retard',
      invoice: 'facture',
      invoices: 'factures',
      loading: 'Chargement du tableau de bord...',
    },
    // Invoices
    invoices: {
      title: 'Factures',
      subtitle: 'Gérez vos factures et devis',
      newInvoice: 'Nouvelle facture',
      search: 'Rechercher (numéro, client)...',
      number: 'Numéro',
      client: 'Client',
      date: 'Date',
      due: 'Échéance',
      status: 'Statut',
      total: 'Total TTC',
      actions: 'Actions',
      markPaid: 'Marquer payée',
      send: 'Envoyer par email',
      download: 'Télécharger PDF',
      duplicate: 'Dupliquer',
      noInvoice: 'Aucune facture',
      createFirst: 'Créer ma première facture',
      loading: 'Chargement...',
      paid: 'Facture payée',
      emailSent: 'Email envoyé',
      duplicated: 'Facture dupliquée',
      error: 'Erreur',
    },
    // Status
    status: {
      BROUILLON: 'Brouillon',
      ENVOYEE: 'Envoyée',
      PAYEE: 'Payée',
      EN_RETARD: 'En retard',
    },
    // New Invoice
    newInvoice: {
      title: 'Nouvelle facture',
      subtitle: 'Remplissez les informations ci-dessous',
      clientLabel: 'Client *',
      clientPlaceholder: 'Sélectionner un client',
      dateLabel: "Date d'émission *",
      dueLabel: 'Échéance *',
      lines: 'Lignes de la facture',
      addLine: 'Ajouter une ligne',
      description: 'Description',
      qty: 'Qté',
      unitPrice: 'Prix HT',
      vat: 'TVA %',
      lineTotal: 'Total HT',
      notes: 'Notes & Conditions',
      notesPlaceholder: "Conditions de paiement, IBAN, pénalités de retard...",
      totalHT: 'Total HT',
      totalVAT: 'TVA',
      totalTTC: 'Total TTC',
      save: 'Enregistrer la facture',
      saving: 'Création en cours...',
      back: 'Retour',
      created: 'Facture créée !',
    },
    // Clients
    clients: {
      title: 'Clients',
      newClient: 'Nouveau client',
      search: 'Rechercher par nom ou email...',
      name: 'Client',
      email: 'Email',
      phone: 'Téléphone',
      siret: 'SIRET',
      invoiceCount: 'Factures',
      actions: 'Actions',
      edit: 'Modifier',
      delete: 'Supprimer',
      noClient: 'Aucun client trouvé',
      noClientSub: 'Créez votre premier client pour commencer',
      addClient: 'Ajouter un client',
      deleteTitle: 'Supprimer ce client ?',
      deleteMsg: 'Cette action est irréversible. Le client sera archivé (soft delete).',
      cancel: 'Annuler',
      confirmDelete: 'Supprimer',
      loading: 'Chargement...',
      deleted: 'Client supprimé',
    },
    // Client modal
    clientModal: {
      create: 'Nouveau client',
      edit: 'Modifier le client',
      name: 'Nom *',
      email: 'Email',
      phone: 'Téléphone',
      address: 'Adresse',
      siret: 'SIRET',
      namePlaceholder: 'Jean Dupont',
      emailPlaceholder: 'jean@exemple.fr',
      phonePlaceholder: '+33 6 12 34 56 78',
      addressPlaceholder: '12 Rue de la Paix, 75001 Paris',
      siretPlaceholder: '12345678901234',
      cancel: 'Annuler',
      createBtn: 'Créer le client',
      editBtn: 'Mettre à jour',
      saving: 'Enregistrement...',
    },
    // Profile
    profile: {
      title: 'Mon Profil',
      subtitle: 'Gérez les informations de votre entreprise',
      company: "Nom de l'entreprise",
      phone: 'Téléphone',
      address: 'Adresse complète',
      siret: 'SIRET',
      rib: 'IBAN / RIB',
      ribHint: 'Sera affiché sur vos factures',
      save: 'Enregistrer les modifications',
      saving: 'Enregistrement...',
      loading: 'Chargement...',
    },
    // Settings bar
    settings: {
      darkMode: 'Mode sombre',
      language: 'Langue',
    },
    common: {
      error: 'Erreur',
      loading: 'Chargement...',
    },
    landing: {
      navLogin: 'Se connecter',
      navTry: 'Essayer gratuitement',
      badge: 'Solution n°1 pour freelancers',
      heroTitle: 'Facturez ',
      heroTitleAccent: 'plus vite',
      heroTitleEnd: ', sans casse-tête.',
      heroDesc: 'Simplifiez votre gestion, suivez vos paiements et créez des factures professionnelles en quelques secondes. Tout ce dont vous avez besoin pour piloter votre activité.',
      getStarted: 'Commencer maintenant',
      viewDemo: 'Voir la démo',
      trustText: 'Plus de 2 000+ freelances nous font confiance.',
      statInvoices: 'Factures créées',
      statUsers: 'Utilisateurs',
      statRevenue: 'CA facturé',
      statSatisfaction: 'Satisfaction',
      featuresTitle: "Tout ce qu'il vous faut.",
      featuresDesc: "Des outils puissants conçus pour la simplicité, pour que vous puissiez vous concentrer sur votre métier.",
      feature1Title: "Édition Ultra-Rapide",
      feature1Desc: "Gérez vos lignes de facturation, taxes et remises en un clin d'œil avec notre éditeur intelligent.",
      feature2Title: "Tableaux de bord",
      feature2Desc: "Visualisez votre chiffre d'affaires, vos encaissements et vos prévisions en temps réel.",
      feature3Title: "Conformité Totale",
      feature3Desc: "Générez des PDF certifiés conformes aux normes fiscales françaises et européennes.",
      feature4Title: "Gestion Clients",
      feature4Desc: "Conservez tout votre historique client et suivez leur comportement de paiement.",
      feature5Title: "Multi-Langues",
      feature5Desc: "Envoyez des factures en Français ou en Anglais selon les besoins de vos partenaires.",
      feature6Title: "Suivi des Paiements",
      feature6Desc: "Soyez alerté dès qu'une facture arrive à échéance ou qu'elle accuse un retard de paiement.",
      ctaTitle: 'Prêt à booster votre business ?',
      ctaDesc: 'Rejoignez des milliers de freelances qui ont déjà automatisé leur facturation. Pas de CB requise.',
      ctaBtn: 'Créer mon compte',
      footerDesc: "La plateforme de facturation simple, intuitive et sécurisée pour les indépendants qui veulent se concentrer sur l'essentiel.",
      footerProduct: 'Produit',
      footerProductLinks: ['Prix', 'Fonctionnalités', 'Sécurité'],
      footerCompany: 'Entreprise',
      footerCompanyLinks: ['À propos', 'Blog', 'Contact'],
      footerLegal: 'Légal',
      footerLegalLinks: ['Mentions légales', 'Confidentialité', 'Cookies'],
      footerCopyright: 'InvoicePro — Made with ❤️ for freelancers.',
    }
  },
  en: {
    nav: {
      dashboard: 'Dashboard',
      clients: 'Clients',
      invoices: 'Invoices',
      newInvoice: 'New invoice',
      profile: 'My profile',
      logout: 'Log out',
    },
    auth: {
      login: 'Login',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      company: 'Company name',
      companyPlaceholder: 'My Creative Studio',
      emailPlaceholder: 'you@example.com',
      loginBtn: 'Sign in',
      registerBtn: 'Create my account',
      logging: 'Signing in...',
      creating: 'Creating...',
      loginTitle: 'Welcome back!',
      registerTitle: 'Create an account',
      loginSubtitle: 'Sign in to access your dashboard',
      registerSubtitle: 'Start invoicing for free in 30 seconds',
      terms: 'By creating an account, you agree to our terms of service.',
      heroTitle: 'Your invoices,',
      heroSubtitle: 'in 2 minutes.',
      heroDesc: 'The SaaS platform built for freelancers. Create, send, and track invoices like a pro.',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Overview of your activity',
      totalRevenue: 'Total revenue',
      collected: 'Collected revenue',
      toCashIn: 'To collect',
      activeClients: 'Active clients',
      revenueChart: 'Monthly collected revenue',
      statusChart: 'Invoice status breakdown',
      topClients: 'Top clients',
      noData: 'No data — mark invoices as paid to see the chart.',
      noInvoice: 'No invoices yet.',
      total: 'Total',
      drafts: 'Drafts',
      sent: 'Sent',
      late: 'Overdue',
      invoice: 'invoice',
      invoices: 'invoices',
      loading: 'Loading dashboard...',
    },
    invoices: {
      title: 'Invoices',
      subtitle: 'Manage your invoices and quotes',
      newInvoice: 'New invoice',
      search: 'Search (number, client)...',
      number: 'Number',
      client: 'Client',
      date: 'Date',
      due: 'Due date',
      status: 'Status',
      total: 'Total incl. VAT',
      actions: 'Actions',
      markPaid: 'Mark as paid',
      send: 'Send by email',
      download: 'Download PDF',
      duplicate: 'Duplicate',
      noInvoice: 'No invoices',
      createFirst: 'Create my first invoice',
      loading: 'Loading...',
      paid: 'Invoice marked as paid',
      emailSent: 'Email sent',
      duplicated: 'Invoice duplicated',
      error: 'Error',
    },
    status: {
      BROUILLON: 'Draft',
      ENVOYEE: 'Sent',
      PAYEE: 'Paid',
      EN_RETARD: 'Overdue',
    },
    newInvoice: {
      title: 'New invoice',
      subtitle: 'Fill in the information below',
      clientLabel: 'Client *',
      clientPlaceholder: 'Select a client',
      dateLabel: 'Issue date *',
      dueLabel: 'Due date *',
      lines: 'Invoice lines',
      addLine: 'Add a line',
      description: 'Description',
      qty: 'Qty',
      unitPrice: 'Unit price',
      vat: 'VAT %',
      lineTotal: 'Line total',
      notes: 'Notes & Terms',
      notesPlaceholder: 'Payment terms, IBAN, late fees...',
      totalHT: 'Subtotal',
      totalVAT: 'VAT',
      totalTTC: 'Total incl. VAT',
      save: 'Save invoice',
      saving: 'Creating...',
      back: 'Back',
      created: 'Invoice created!',
    },
    clients: {
      title: 'Clients',
      newClient: 'New client',
      search: 'Search by name or email...',
      name: 'Client',
      email: 'Email',
      phone: 'Phone',
      siret: 'Company ID',
      invoiceCount: 'Invoices',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      noClient: 'No clients found',
      noClientSub: 'Create your first client to get started',
      addClient: 'Add a client',
      deleteTitle: 'Delete this client?',
      deleteMsg: 'This action is irreversible. The client will be archived.',
      cancel: 'Cancel',
      confirmDelete: 'Delete',
      loading: 'Loading...',
      deleted: 'Client deleted',
    },
    clientModal: {
      create: 'New client',
      edit: 'Edit client',
      name: 'Name *',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      siret: 'Company ID',
      namePlaceholder: 'John Doe',
      emailPlaceholder: 'john@example.com',
      phonePlaceholder: '+1 234 567 8900',
      addressPlaceholder: '123 Main St, New York, NY',
      siretPlaceholder: '12345678901234',
      cancel: 'Cancel',
      createBtn: 'Create client',
      editBtn: 'Update',
      saving: 'Saving...',
    },
    profile: {
      title: 'My Profile',
      subtitle: 'Manage your business information',
      company: 'Company name',
      phone: 'Phone',
      address: 'Full address',
      siret: 'Company ID',
      rib: 'IBAN',
      ribHint: 'Will appear on your invoices',
      save: 'Save changes',
      saving: 'Saving...',
      loading: 'Loading...',
    },
    settings: {
      darkMode: 'Dark mode',
      language: 'Language',
    },
    common: {
      error: 'Error',
      loading: 'Loading...',
    },
    landing: {
      navLogin: 'Login',
      navTry: 'Try for free',
      badge: '#1 Solution for freelancers',
      heroTitle: 'Invoice ',
      heroTitleAccent: 'faster',
      heroTitleEnd: ', without the headache.',
      heroDesc: 'Simplify your management, track your payments and create professional invoices in seconds. Everything you need to run your business.',
      getStarted: 'Get started now',
      viewDemo: 'View demo',
      trustText: 'Trusted by over 2,000+ freelancers.',
      statInvoices: 'Invoices created',
      statUsers: 'Users',
      statRevenue: 'Invoiced revenue',
      statSatisfaction: 'Satisfaction',
      featuresTitle: 'Everything you need.',
      featuresDesc: 'Powerful tools designed for simplicity, so you can focus on your craft.',
      feature1Title: 'Ultra-Fast Editing',
      feature1Desc: 'Manage your billing lines, taxes, and discounts in the blink of an eye with our smart editor.',
      feature2Title: 'Dashboards',
      feature2Desc: 'Visualize your revenue, collections, and forecasts in real-time.',
      feature3Title: 'Full Compliance',
      feature3Desc: 'Generate certified PDF invoices compliant with tax standards.',
      feature4Title: 'Client Management',
      feature4Desc: 'Keep all your client history and track their payment behavior.',
      feature5Title: 'Multi-Language',
      feature5Desc: 'Send invoices in French or English according to your partners\' needs.',
      feature6Title: 'Payment Tracking',
      feature6Desc: 'Be alerted as soon as an invoice is due or overdue.',
      ctaTitle: 'Ready to boost your business?',
      ctaDesc: 'Join thousands of freelancers who have already automated their billing. No credit card required.',
      ctaBtn: 'Create my account',
      footerDesc: 'The simple, intuitive, and secure invoicing platform for independent workers who want to focus on what matters.',
      footerProduct: 'Product',
      footerProductLinks: ['Pricing', 'Features', 'Security'],
      footerCompany: 'Company',
      footerCompanyLinks: ['About', 'Blog', 'Contact'],
      footerLegal: 'Legal',
      footerLegalLinks: ['Legal Notice', 'Privacy', 'Cookies'],
      footerCopyright: 'InvoicePro — Made with ❤️ for freelancers.',
    }
  }
} as const;

export type Lang = 'fr' | 'en';
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Translations = Record<string, any>;

// ─── Context ──────────────────────────────────────────────────────────────────
interface AppSettings {
  lang: Lang;
  darkMode: boolean;
  setLang: (l: Lang) => void;
  toggleDark: () => void;
  t: Translations;
}

const SettingsContext = createContext<AppSettings | null>(null);

export const SettingsProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || 'fr');
  const [darkMode, setDarkMode] = useState<boolean>(() => {
    const saved = localStorage.getItem('darkMode');
    return saved !== null ? saved === 'true' : true; // dark by default
  });

  useEffect(() => {
    document.body.classList.toggle('light', !darkMode);
    localStorage.setItem('darkMode', String(darkMode));
  }, [darkMode]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const toggleDark = () => setDarkMode(d => !d);

  return (
    <SettingsContext.Provider value={{ lang, darkMode, setLang, toggleDark, t: translations[lang] }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error('useSettings must be inside SettingsProvider');
  return ctx;
};
