spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-falling-butterfly-amnawtoc-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_2AVWmi6vNbxE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    # Configuration SMTP Gmail
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    protocol: ${SMTP_PROTOCOL:}
    default-encoding: ${SMTP_ENCODING:}

    # Propriétés SMTP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          starttls.required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl.trust: smtp.gmail.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:8080}

application:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # 24 heures en ms
  frontend-url: ${FRONTEND_URL:https://invoice-pro-henna.vercel.app}
  upload-dir: ${UPLOAD_DIR:./uploads}
